# Generated by Django 2.1.5 on 2025-03-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpetinfo',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='postpetinfo',
            name='has_landlord_permission',
        ),
        migrations.RemoveField(
            model_name='postpetinfo',
            name='operator_username',
        ),
    ]
