# Generated by Django 2.1.5 on 2025-03-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20250315_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(choices=[('Young', 'Young'), ('Adult', 'Adult')], max_length=10),
        ),
    ]
