# Generated by Django 2.1.5 on 2025-03-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20250315_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='pet_image',
            field=models.ImageField(upload_to='petPhotos'),
        ),
    ]
