# Generated by Django 2.1.5 on 2025-03-16 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20250315_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpetinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
