# Generated by Django 2.1.5 on 2025-03-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20250316_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='pet_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/pet_images/'),
        ),
    ]
