# Generated by Django 2.1.5 on 2025-03-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20250316_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpetinfo',
            name='review_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
