# Generated by Django 2.1.5 on 2025-03-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postpetinfo_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpetinfo',
            name='experience_with_pets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postpetinfo',
            name='has_children',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='postpetinfo',
            name='has_other_pets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postpetinfo',
            name='home_ownership',
            field=models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent'), ('Living with parents', 'Living with parents'), ('Other', 'Other')], default='Own', max_length=20),
        ),
        migrations.AlterField(
            model_name='postpetinfo',
            name='home_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Townhouse', 'Townhouse'), ('Other', 'Other')], default='Apartment', max_length=20),
        ),
        migrations.AlterField(
            model_name='postpetinfo',
            name='pet_passport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postpetinfo',
            name='vaccinated',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
    ]
