# Generated by Django 2.1.5 on 2025-03-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20250317_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpetinfo',
            name='home_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Townhouse', 'Townhouse'), ('Farm/Rural', 'Farm/Rural')], default='Apartment', max_length=20),
        ),
    ]
