# Generated by Django 2.1.5 on 2025-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20250317_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpetinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
