# Generated by Django 2.1.5 on 2025-03-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20250317_2102'),
        ('posts', '0011_auto_20250318_1533'),
    ]

    operations = [
    ]
