# Generated by Django 2.1.5 on 2025-03-19 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_merge_20250318_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreview',
            name='pet_id',
        ),
        migrations.AddField(
            model_name='postreview',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Pet'),
            preserve_default=False,
        ),
    ]
