# Generated by Django 5.1.6 on 2025-03-05 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin_dashboard", "0001_initial"),
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptionReview",
            fields=[
                (
                    "adopt_review_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "adopter_username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adoption_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operator_username",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posts.pet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdoptPetInfo",
            fields=[
                ("adopt_info_id", models.AutoField(primary_key=True, serialize=False)),
                ("home_type", models.CharField(max_length=50)),
                ("home_ownership", models.CharField(max_length=50)),
                ("has_landlord_permission", models.BooleanField(default=False)),
                ("has_other_pets", models.BooleanField(default=False)),
                ("has_children", models.BooleanField(default=False)),
                ("experience_with_pets", models.BooleanField(default=False)),
                ("reason_for_adoption", models.CharField(max_length=200)),
                ("vaccinated", models.BooleanField(default=False)),
                ("pet_passport", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_adoptions",
                        to="admin_dashboard.users",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_dashboard.pets",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adopted_pets",
                        to="admin_dashboard.users",
                    ),
                ),
            ],
        ),
    ]
