# Generated by Django 2.1.5 on 2025-03-18 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptpetinfo',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_adoptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adoptpetinfo',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Pet'),
        ),
        migrations.AlterField(
            model_name='adoptpetinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopted_pets', to=settings.AUTH_USER_MODEL),
        ),
    ]
