# Generated by Django 2.1.5 on 2025-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_auto_20250318_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptpetinfo',
            name='vaccinated',
        ),
        migrations.AlterField(
            model_name='adoptpetinfo',
            name='experience_with_pets',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adoptpetinfo',
            name='has_children',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptpetinfo',
            name='has_other_pets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adoptpetinfo',
            name='reason_for_adoption',
            field=models.TextField(blank=True),
        ),
    ]
