# Generated by Django 2.1.5 on 2025-03-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0003_auto_20250318_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptpetinfo',
            name='experience_with_pets',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='adoptpetinfo',
            name='reason_for_adoption',
            field=models.TextField(),
        ),
    ]
