# Generated by Django 2.1.5 on 2025-03-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0005_adoptionreview_adopt_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionreview',
            name='experience_with_pets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adoptionreview',
            name='has_children',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='adoptionreview',
            name='home_ownership',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adoptionreview',
            name='home_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adoptionreview',
            name='reason_for_adoption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
