# Generated by Django 2.1.5 on 2025-03-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0006_auto_20250318_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionreview',
            name='adopt_info',
        ),
    ]
