# Generated by Django 2.1.5 on 2025-03-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0007_remove_adoptionreview_adopt_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionreview',
            name='adopt_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='adoptions.AdoptPetInfo'),
        ),
    ]
