# Generated by Django 2.1.5 on 2025-03-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0008_adoptionreview_adopt_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionreview',
            name='review_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
