# Generated by Django 2.1.5 on 2025-03-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0009_adoptionreview_review_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionreview',
            name='experience_with_pets',
        ),
        migrations.RemoveField(
            model_name='adoptionreview',
            name='has_children',
        ),
        migrations.RemoveField(
            model_name='adoptionreview',
            name='home_ownership',
        ),
        migrations.RemoveField(
            model_name='adoptionreview',
            name='home_type',
        ),
        migrations.RemoveField(
            model_name='adoptionreview',
            name='reason_for_adoption',
        ),
    ]
