# Generated by Django 2.1.5 on 2025-03-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0010_auto_20250319_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptpetinfo',
            name='pet_passport',
        ),
    ]
